const ProjectData = [
    {
        "id": 1,
        "title": "New Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 2,
        "title": "NOt Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 3,
        "title": "Auto Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    
    {
        "id": 4,
        "title": "Last Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 5,
        "title": "Sigh Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 6,
        "title": "All Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 7,
        "title": "JS Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 8,
        "title": "CSS Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 9,
        "title": "Kinda Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 10,
        "title": "Skull Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 11,
        "title": "Obtain Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    },
    {
        "id": 12,
        "title": "Pant Project",
        "img": "https://images.pexels.com/photos/16971942/pexels-photo-16971942/free-photo-of-black-and-white-picture-of-foamy-waves.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi saepe tenetur ipsum aut quaerat blanditiis vitae. Dolores quasi deserunt, delectus quia similique quam magnam ipsa hic quas, natus facere repudiandae ipsam corrupti eos minima officia, praesentium recusandae sed odit tenetur.",
        "tech": ["API", "React.JS", "Bootstrap"],
        "url": "gym-note.vercel.app",
    }
]

export default ProjectData